name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lsp-server:
    name: LSP Server
    runs-on: docker
    steps:
      - id: checkout
        name: Checkout rep0
        uses: https://github.com/actions/checkout@v7

      - id: setup-rust
        name: Setup Rust
        uses: https://github.com/dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - id: clippy
        name: Run clippy
        run: cargo zrl-srv-lint-alltargets

      - id: buildem
        name: Build that shit
        run: cargo zrl-srv-build-alltargets

  extension:
    name: Extension
    runs-on: docker
    steps:
      - id: checkout
        name: Checkout rep0
        uses: https://github.com/actions/checkout@v7

      - id: setup-rust
        name: Setup Rust
        uses: https://github.com/dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-wasip2
          components: clippy

      - id: clippy
        name: Run clippy
        run: cargo zrl-ext-lint

      - id: buildem
        name: Build that shit
        run: cargo zrl-ext-build
