name: Ren0vatem

on:
  push: # TODO: for testing obviously lol
    branches:
      - master
  #schedule:
  #  - cron: '2 * * * *'

jobs:
  ren0vatem:
    runs-on: docker
    container:
      image: ghcr.io/renovatebot/renovate:43
      options: --tmpfs /tmp:exec
    steps:
      #- id: checkout
      #  name: Checkout rep0
      #  uses: https://github.com/actions/checkout@v7

      - id: renovate
        name: Run Renovate
        run: renovate
        env:
          LOG_LEVEL: debug # TODO: for testing obviously lol
          RENOVATE_ENDPOINT: ${{ forgejo.server_url }}
          RENOVATE_TOKEN: ${{ secrets.RENOVATEM_TOKEN }}
          RENOVATE_PLATFORM: 'forgejo'
          RENOVATE_REPOSITORIES: '["${{ forgejo.repository }}"]'
          RENOVATE_BRANCH_PREFIX: 'ren0vatem-'
          RENOVATE_DRY_RUN: 'full' # TODO: for testing obviously lol
          RENOVATE_ONBOARDING: false
          RENOVATE_REQUIRE_CONFIG: 'optional'
