name: Ren0vatem

on:
  push: # TODO: for testing obviously lol
    branches:
      - master
  schedule:
    - cron: '30 */8 * * *'

jobs:
  ren0vatem:
    runs-on: docker
    container:
      image: ghcr.io/renovatebot/renovate:43
      options: --tmpfs /tmp:exec
    steps:
      - id: renovate
        name: Run Renovate
        run: renovate
        env:
          RENOVATE_PLATFORM: 'forgejo'
          RENOVATE_ENDPOINT: ${{ forgejo.server_url }}
          RENOVATE_TOKEN: ${{ secrets.RENOVATEM_TOKEN }}
          RENOVATE_GITHUB_COM_TOKEN: ${{ secrets.RENOVATEM_GITHUB_TOKEN }}
          RENOVATE_REPOSITORIES: '["${{ forgejo.repository }}"]'
          RENOVATE_BRANCH_PREFIX: 'ren0vatem-'
          RENOVATE_ONBOARDING: false
          RENOVATE_REQUIRE_CONFIG: 'optional'
