name: Stale issues/PRs

on:
  schedule:
    - cron: '20 */4 * * *'

jobs:
  stale:
    runs-on: docker
    steps:
      - id: stale
        name: Checkem stale issues/PRs
        uses: https://github.com/actions/stale@v10
        with:
          days-before-issue-stale: 60
          days-before-issue-close: 7
          stale-issue-message: "This issue was automatically marked as stale because there hasn't been any activity for 60 days. This issue will be closed in 7 days if no further activity occurs."
          close-issue-message: 'This issue was automatically closed because no further activity occurred.'
          exempt-issue-labels: Kind/Bug,Kind/Security,Priority/Critical,Priority/High,Reviewed/Confirmed,Status/Blocked

          days-before-pr-stale: 90
          days-before-pr-close: 7
          stale-pr-message: "This PR was automatically marked as stale because there hasn't been any activity for 90 days. This PR will be closed in 7 days if no further activity occurs."
          close-pr-message: 'This PR was automatically closed because no further activity occurred.'
          exempt-pr-labels: Kind/Bug,Kind/Security,Priority/Critical,Priority/High,Reviewed/Confirmed,Status/Blocked

          ascending: true
